/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Test } from "./Test";
export type { Test1 } from "./Test1";
export * as factories from "./factories";
export { Test__factory } from "./factories/Test__factory";
export { Test1__factory } from "./factories/Test1__factory";
