/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Test1, Test1Interface } from "../Test1";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "store1",
    outputs: [
      {
        internalType: "bool",
        name: "_res",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "retrieve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Test1__factory {
  static readonly abi = _abi;
  static createInterface(): Test1Interface {
    return new utils.Interface(_abi) as Test1Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Test1 {
    return new Contract(address, _abi, signerOrProvider) as Test1;
  }
}
